name: NodeJS CI

on: push

jobs:
 build:
   runs-on: windows-latest
   strategy:
     matrix:
       node-version: [18.x]

   steps:
     - name: Checkout repository
       uses: actions/checkout@v4
     - name: Use Node.js [18.x]
       uses: actions/setup-node@v2
       with:
         node-version: ${{ matrix.node-version }}
     - name: Unit checks
       run: |
         npm ci
         npm test
     - name: E2E checks
       run: |
         npm start &
         curl --head -X GET --retry 60 --retry-connrefused --retry-delay 1 http://localhost:3000
         npx wdio run ./wdio.conf.js
     - name: Build production artifacts
       run: |
         npm run build --if-present

